sudo: false
language: ruby
rvm: 2.2

env:
  global:
    - secure: "CD9mNKFgQTq12JVViWBL43hviuh2565ayA+uFZ0cxdNydEr+31UD+t0bVxZRDeZklgIlK5v5fhb4jTMFD6CD3j+/IUq9jXytjPjPf3APcj7D5uDoEtmt1n8y7bEAKQO6nbeLWLyUnFzVXY5kedJNrpzCz2tSwkQ1+4ZeZloQSwg="

jdk:
  - oraclejdk8

install:
  - bundle install
  - curl -s https://raw.githubusercontent.com/paulp/sbt-extras/master/sbt -o sbt
  - chmod +x sbt

script:
  - ./sbt run
  - bundle exec jekyll build

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

branches:
  except:
    - master

deploy:
  - provider: script
    script: ./deploy.sh
    skip_cleanup: true
    on:
      branch: development
